version: '3'

services:
    mysql:
        image: mariadb:latest
        container_name: mysql
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - "mysql:/var/lib/mysql"
        environment:
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - backend

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
        volumes:
            - "redis:/data"
        networks:
            - backend

    nc:
        image: nextcloud:21-fpm
        container_name: nc
        restart: always
        volumes:
            - "nc:/var/www/html"
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
            - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
            - REDIS_HOST=redis
            - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
            - PHP_MEMORY_LIMIT=2G
            - PHP_UPLOAD_LIMIT=100G
        depends_on:
            - mysql
            - redis
        networks:
            - frontend
            - backend

    proxy:
        image: nginx:latest
        container_name: proxy
        restart: always
        ports:
            - 80:80
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
        depends_on:
            - nc
        networks:
            - frontend

volumes:
    mysql:
    redis:
    nc:

networks:
    frontend:
    backend:
